apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: techtrends
  type: {{ .Values.service.type }}